### ISSUE TITLE
Console Error on 1.19.4 

### ISSUE THREAD

**Issue by DarkSlayer995** [bbb907/EagleAC-API#2]
Hello, I have a Console Error regarding the Plugin when using commands: 

Error Paste: https://pastebin.com/N8CicF5q

![image](https://github.com/user-attachments/assets/dd1ef52f-dd67-4593-8315-e8f3fc78885e)

**Comment by bbb908** [comment]
Ah sorry about that be sure to do /eagle reload and /eagle alerts only for now I'll get that fixed next update

**Comment by DarkSlayer995** [comment]
Alright Thank you!

**Comment by xXGamerHDXTv** [comment]
Also, I found an Error when someone is hacking (using Inventory Move) The anticheat detects the player to be cheating but spamming errors:

pastebin: https://pastebin.com/SyN7irt6

**Comment by bbb907** [comment]
Resolved in the premium version will be pushed to the Lite version tmr
